repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-merge-conflict
  - id: check-added-large-files
    exclude: >-
      (?x)(
        uv.lock|
        aiida-atomistic/tests/static/
      )
  - id: check-yaml
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
    exclude: &exclude_pre_commit_hooks >
      (?x)^(
        aiida-core/tests/.*(?<!\.py)$|
        aiida-core/docs/source/.+\.aiida/repo/.+|
        CHANGELOG.md|
      )$
  - id: fix-encoding-pragma
    args: [--remove]
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: trailing-whitespace
    exclude: *exclude_pre_commit_hooks

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.30.0
  hooks:
  - id: check-github-workflows

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.21
  hooks:
  - id: ruff-format
    args: [--config=ruff.toml]
  - id: ruff-check
    args: [--config=ruff.toml, --fix, --exit-non-zero-on-fix, --show-fixes]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
    exclude: uv.lock
  - id: pretty-format-yaml
    args: [--autofix]
    exclude: >-
      (?x)^(
        aiida-core/tests/.*|
        aiida-core/environment.yml|
      )$

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.11.21
  hooks:
    # Check and update the uv lockfile
  - id: uv-lock
    args: [--project, aiida-core]
    files: ^aiida-core/(uv\.lock|pyproject\.toml)$
  - id: uv-lock
    args: [--project, aiida-atomistic]
    files: ^aiida-atomistic/(uv\.lock|pyproject\.toml)$

- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
  - id: nbstripout
    files: \.ipynb$

- repo: local

  hooks:

  - id: mypy
    name: mypy
    entry: mypy
    args: [--config-file=mypy.toml, --pretty]
    language: python
    types: [python]
    require_serial: true
    pass_filenames: true
    exclude: >-
      (?x)^(
        .github/.*|
        .molecule/.*|
        .docker/.*|
        aiida-core/docs/.*|
        utils/.*|
        aiida-core/tests/.*|

        aiida-core/src/aiida/calculations/arithmetic/add.py|
        aiida-core/src/aiida/calculations/diff_tutorial/calculations.py|
        aiida-core/src/aiida/calculations/templatereplacer.py|
        aiida-core/src/aiida/calculations/transfer.py|
        aiida-core/src/aiida/engine/daemon/execmanager.py|
        aiida-core/src/aiida/manage/configuration/__init__.py|
        aiida-core/src/aiida/manage/configuration/config.py|
        aiida-core/src/aiida/manage/external/rmq/launcher.py|
        aiida-core/src/aiida/orm/nodes/data/cif.py|
        aiida-core/src/aiida/orm/nodes/data/remote/base.py|
        aiida-core/src/aiida/orm/nodes/data/structure.py|
        aiida-core/src/aiida/orm/nodes/data/upf.py|
        aiida-core/src/aiida/orm/nodes/process/calculation/calcjob.py|
        aiida-core/src/aiida/orm/nodes/process/process.py|
        aiida-core/src/aiida/orm/utils/builders/code.py|
        aiida-core/src/aiida/orm/utils/builders/computer.py|
        aiida-core/src/aiida/orm/utils/calcjob.py|
        aiida-core/src/aiida/orm/utils/node.py|
        aiida-core/src/aiida/restapi/common/utils.py|
        aiida-core/src/aiida/restapi/resources.py|
        aiida-core/src/aiida/restapi/run_api.py|
        aiida-core/src/aiida/restapi/translator/base.py|
        aiida-core/src/aiida/restapi/translator/computer.py|
        aiida-core/src/aiida/restapi/translator/group.py|
        aiida-core/src/aiida/restapi/translator/nodes/.*|
        aiida-core/src/aiida/restapi/translator/user.py|
        aiida-core/src/aiida/storage/psql_dos/migrations/utils/integrity.py|
        aiida-core/src/aiida/storage/psql_dos/migrations/utils/legacy_workflows.py|
        aiida-core/src/aiida/storage/psql_dos/migrations/utils/migrate_repository.py|
        aiida-core/src/aiida/storage/psql_dos/migrations/utils/parity.py|
        aiida-core/src/aiida/storage/psql_dos/migrations/utils/reflect.py|
        aiida-core/src/aiida/storage/psql_dos/migrations/utils/utils.py|
        aiida-core/src/aiida/storage/psql_dos/migrations/versions/1de112340b16_django_parity_1.py|
        aiida-core/src/aiida/storage/psql_dos/models/.*|
        aiida-core/src/aiida/storage/psql_dos/orm/.*.py|
        aiida-core/src/aiida/storage/psql_dos/orm/querybuilder/joiner.py|
        aiida-core/src/aiida/storage/sqlite_zip/migrations/legacy_to_main.py|
        aiida-core/src/aiida/storage/sqlite_zip/models.py|
        aiida-core/src/aiida/storage/sqlite_zip/orm.py|
        aiida-core/src/aiida/tools/data/array/kpoints/legacy.py|
        aiida-core/src/aiida/tools/data/array/kpoints/seekpath.py|
        aiida-core/src/aiida/tools/data/orbital/orbital.py|
        aiida-core/src/aiida/tools/data/orbital/realhydrogen.py|
        aiida-core/src/aiida/tools/dbimporters/plugins/.*|
        aiida-core/src/aiida/transports/cli.py|
        aiida-core/src/aiida/transports/plugins/local.py|
        aiida-core/src/aiida/transports/plugins/ssh.py|
      )$

  - id: generate-conda-environment
    name: Update conda environment file
    entry: python ./utils/dependency_management.py generate-environment-yml
    language: system
    pass_filenames: false
    files: >-
      (?x)^(
        aiida-core/pyproject.toml|
        utils/dependency_management.py|
        aiida-core/environment.yml|
      )$

  - id: validate-conda-environment
    name: Validate aiida-core/environment.yml
    entry: python ./utils/dependency_management.py validate-environment-yml
    language: system
    pass_filenames: false
    files: >-
      (?x)^(
        aiida-core/pyproject.toml|
        utils/dependency_management.py|
        aiida-core/environment.yml|
      )$

  - id: verdi-autodocs
    name: Automatically generating verdi docs
    entry: python ./utils/validate_consistency.py verdi-autodocs
    language: system
    pass_filenames: false
    files: >-
      (?x)^(
        aiida-core/src/aiida/cmdline/commands/.*|
        aiida-core/src/aiida/cmdline/params/.*|
        aiida-core/src/aiida/cmdline/params/types/.*|
        utils/validate_consistency.py|
      )$
