version: 2

# Important: we need to disable all unneeded formats.
# Note that HTML and JSON are always built: https://docs.readthedocs.io/en/latest/yaml-config.html#formats
# Especially, the 'htmlzip' format takes a LOT of memory and causes the build to fail - see our issue #1472:
# https://github.com/aiidateam/aiida-core/issues/1472
formats: []

build:
  apt_packages:
  - graphviz
  os: ubuntu-22.04
  tools:
    python: '3.11'
  jobs:
    # Use uv to speed up the build
    # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
    post_create_environment:
    - asdf plugin add uv
    - asdf install uv 0.2.9
    - asdf global uv 0.2.9
    post_install:
    - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv pip install .[docs,tests,rest,atomic_tools]

# Let the build fail if there are any warnings
sphinx:
  builder: html
  fail_on_warning: true

search:
  ranking:
    reference/apidoc/*: -7
