version: 2

# Important: we need to disable all unneeded formats.
# Note that HTML and JSON are always built: https://docs.readthedocs.io/en/latest/yaml-config.html#formats
# Especially, the 'htmlzip' format takes a LOT of memory and causes the build to fail - see our issue #1472:
# https://github.com/aiidateam/aiida-core/issues/1472
formats: []

build:
  apt_packages:
    - graphviz
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Need to install the package itself such that the entry points are installed and the API doc can build properly
python:
    install:
        - method: pip
          path: .
          extra_requirements:
            - docs
            - tests
            - rest
            - atomic_tools

# Let the build fail if there are any warnings
sphinx:
    builder: html
    fail_on_warning: true

search:
  ranking:
    reference/apidoc/*: -7
