version: 2

# Important: we need to disable all unneeded formats.
# Note that HTML and JSON are always built: https://docs.readthedocs.io/en/latest/yaml-config.html#formats
# Especially, the 'htmlzip' format takes a LOT of memory and causes the build to fail - see our issue #1472:
# https://github.com/aiidateam/aiida-core/issues/1472
formats: []

build:
  apt_packages:
  - graphviz
  os: ubuntu-22.04
  tools:
    python: '3.11'
  jobs:
    # Use uv to speed up the build
    # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
    pre_create_environment:
    - asdf plugin add uv
    - asdf install uv 0.5.28
    - asdf global uv 0.5.28
    install:
    - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --extra docs --extra tests --extra rest --extra atomic_tools

sphinx:
  builder: html
  fail_on_warning: true
  configuration: docs/source/conf.py

search:
  ranking:
    reference/apidoc/*: -7
