codecov:
  notify:
    after_n_builds: 1
    wait_for_ci: no
  require_ci_to_pass: no

coverage:
  precision: 2  # default, here for transparency
  round: up
  range: 70...100    # default, here for transparency
  status:
    project:
      default:
        threshold: 0.02%
    patch:
      default:
        threshold: 0.1%

ignore:
- src/aiida/tools/_dumping/**/*
