codecov:
  notify:
    after_n_builds: 2
    wait_for_ci: yes
  require_ci_to_pass: yes

coverage:
  precision: 2  # default, here for transparency
  round: up
  range: "70...100"  # default, here for transparency
  status:
    project:
      default:
        threshold: 0.02%
    patch:
      default:
        threshold: 0.1%
