# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 12:00
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations
from aiida.backends.djsite.db.migrations import upgrade_schema_version

REVISION = '1.0.19'
DOWN_REVISION = '1.0.18'


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_django_1_11'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbgroup',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='dbgroup',
            old_name='type',
            new_name='type_string',
        ),
        migrations.AlterUniqueTogether(
            name='dbgroup',
            unique_together=set([('label', 'type_string')]),
        ),
        upgrade_schema_version(REVISION, DOWN_REVISION)
    ]
