name: Install aiida-core
description: Install aiida-core package and its Python dependencies

inputs:
  python-version:
    description: Python version
    default: '3.9'              # Lowest supported version
    required: false
  extras:
    description: list of optional dependencies
    # NOTE: The default 'pre-commit' extra recursively contains
    # other extras needed to run the tests.
    default: pre-commit
    required: false
  # NOTE: Hard-learned lesson: we cannot use type=boolean here, apparently :-(
  # https://stackoverflow.com/a/76294014
  # NOTE2: When installing from lockfile, aiida-core and its dependencies
  # are installed in a virtual environment located in .venv directory.
  # Subsuquent jobs steps must either activate the environment or use `uv run`
  from-lock:
    description: Install aiida-core dependencies from uv lock file
    default: 'true'
    required: false

runs:
  using: composite
  steps:
  - name: Set Up Python
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.python-version }}

  - name: Set up uv
    uses: astral-sh/setup-uv@v5.2.1
    with:
      version: 0.5.22
      python-version: ${{ inputs.python-version }}

  - name: Install dependencies from uv lock
    if: ${{ inputs.from-lock == 'true' }}
    # NOTE: We're asserting that the lockfile is up to date
    run: uv sync --locked ${{ inputs.extras && format('--extra {0}', inputs.extras) || '' }}
    shell: bash

  - name: Install aiida-core
    if: ${{ inputs.from-lock != 'true' }}
    run: uv pip install -e .${{ inputs.extras }}
    shell: bash
