name: Install aiida-core
description: Install aiida-core package and its Python dependencies

inputs:
  python-version:
    description: Python version
    default: '3.9'              # Lowest supported version
    required: false
  extras:
    description: aiida-core extras (including brackets)
    default: ''
    required: false
  # NOTE: Hard-learned lesson: we cannot use type=boolean here, apparently :-(
  # https://stackoverflow.com/a/76294014
  # TODO: Rename this to 'from-lock'
  from-requirements:
    description: Install aiida-core dependencies from a uv lock file
    default: 'true'
    required: false

runs:
  using: composite
  steps:
  - name: Set Up Python
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.python-version }}

  - name: Set up uv
    uses: astral-sh/setup-uv@v3
    with:
      version: 0.5.4

  - name: Install dependencies from uv lock
    if: ${{ inputs.from-requirements == 'true' }}
    run: uv sync --locked
    shell: bash

  - name: Install aiida-core
    if: ${{ inputs.from-requirements != 'true' }}
    run: uv pip install --system -e .${{ inputs.extras }}
    shell: bash
