name: Install aiida-core
description: Install aiida-core package and its Python dependencies

inputs:
  python-version:
    description: Python version
    default: '3.9'              # Lowest supported version
    required: false
  extras:
    description: aiida-core extras (including brackets)
    default: ''
    required: false
  # NOTE: Hard-learned lesson: we cannot use type=boolean here, apparently :-(
  # https://stackoverflow.com/a/76294014
  # NOTE2: When installing from lockfile, aiida-core and its dependencies
  # are installed in a virtual environment located in .venv directory.
  # Subsuquent jobs steps must either activate the environment or use `uv run`
  from-lock:
    description: Install aiida-core dependencies from a uv lock file
    default: 'true'
    required: false

runs:
  using: composite
  steps:
  - name: Set Up Python
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.python-version }}

  - name: Set up uv
    uses: astral-sh/setup-uv@v4
    with:
      version: 0.5.6

  - name: Install dependencies from uv lock
    if: ${{ inputs.from-lock == 'true' }}
    # NOTE: We're asserting that the lockfile is up to date
    # NOTE2: 'pre-commit' extra recursively contains other extras
    # needed to run the tests.
    run: uv sync --locked --extra pre-commit
    shell: bash

  - name: Install aiida-core
    if: ${{ inputs.from-lock != 'true' }}
    run: uv pip install --system -e .${{ inputs.extras }}
    shell: bash
