name: Install aiida-core
description: Install aiida-core package and its Python dependencies

inputs:
  python-version:
    description: Python version
    default: '3.9'              # Lowest supported version
    required: false
  extras:
    description: list of optional dependencies
    default: ''
    required: false
  # NOTE: Hard-learned lesson: we cannot use type=boolean here, apparently :-(
  # https://stackoverflow.com/a/76294014
  from-lock:
    description: Install aiida-core dependencies from uv lock file
    default: 'true'
    required: false
  resolution-strategy:
    description: uv dependency resolution strategy
    default: highest
    required: false

runs:
  using: composite
  steps:
  - name: Set Up Python
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.python-version }}

  - name: Set up uv
    uses: astral-sh/setup-uv@v6
    with:
      version: 0.7.6
      python-version: ${{ inputs.python-version }}
      activate-environment: true

  - name: Install dependencies from uv lock
    if: ${{ inputs.from-lock == 'true' }}
    # NOTE: We're asserting that the lockfile is up to date
    run: uv sync --locked ${{ inputs.extras && format('--extra {0}', inputs.extras) || '' }}
    shell: bash

  - name: Install aiida-core
    if: ${{ inputs.from-lock != 'true' }}
    run: |
      uv pip install --resolution ${{ inputs.resolution-strategy }} -e .${{ inputs.extras && format('[{0}]', inputs.extras) || '' }}
    shell: bash
