###########################################################################
# Copyright (c), The AiiDA team. All rights reserved.                     #
# This file is part of the AiiDA code.                                    #
#                                                                         #
# The code is hosted on GitHub at https://github.com/aiidateam/aiida-core #
# For further information on the license, see the LICENSE.txt file        #
# For further information please visit http://www.aiida.net               #
###########################################################################
"""Snapshot test locking the public API surface.

Anything importable from a second-level package (or listed CLI toolkit module) is public API.
This test freezes each ``__all__`` so that any accidental addition, removal or rename of a
public symbol fails CI and requires an explicit, reviewed update of the snapshot below.

To update after an intentional change: adjust the entry here and document the change.
"""

import importlib
import pkgutil

import pytest

import aiida

# Second-level packages that intentionally expose no public API. They must stay surface-free:
# the moment a module inside one gains an ``__all__``, the generator would mint a brand-new public
# surface for the package, so ``test_all_second_level_packages_accounted_for`` forces an explicit
# decision (freeze it in ``PUBLIC_API`` or keep it here) rather than letting it leak silently.
SURFACE_FREE = frozenset(
    {
        'aiida.calculations',
        'aiida.sphinxext',
        'aiida.workflows',
    }
)

PUBLIC_API = {
    'aiida.brokers': (
        'Broker',
        'RabbitmqBroker',
        'ZmqBroker',
    ),
    'aiida.cmdline': (
        'AbsolutePathParamType',
        'CalculationParamType',
        'CodeParamType',
        'ComputerParamType',
        'ConfigOptionParamType',
        'DataParamType',
        'DynamicEntryPointCommandGroup',
        'EmailType',
        'EntryPointType',
        'FileOrUrl',
        'GroupParamType',
        'HostnameType',
        'IdentifierParamType',
        'LabelStringType',
        'LazyChoice',
        'MpirunCommandParamType',
        'MultipleValueParamType',
        'NodeParamType',
        'NonEmptyStringParamType',
        'PathOrUrl',
        'PluginParamType',
        'ProcessParamType',
        'ProfileParamType',
        'ShebangParamType',
        'UserParamType',
        'VerdiCommandGroup',
        'WorkflowParamType',
        'dbenv',
        'echo_critical',
        'echo_dictionary',
        'echo_error',
        'echo_info',
        'echo_report',
        'echo_success',
        'echo_tabulate',
        'echo_warning',
        'format_call_graph',
        'is_verbose',
        'only_if_daemon_running',
        'with_dbenv',
    ),
    'aiida.common': (
        'AIIDA_LOGGER',
        'AiidaDeprecationWarning',
        'AiidaEntryPointWarning',
        'AiidaException',
        'AiidaTestWarning',
        'AttributeDict',
        'CalcInfo',
        'CalcJobState',
        'ClosedStorage',
        'CodeInfo',
        'CodeRunMode',
        'ConfigurationError',
        'ConfigurationVersionError',
        'ContentNotExistent',
        'CorruptStorage',
        'DbContentError',
        'DefaultFieldsAttributeDict',
        'EntryPointError',
        'FailedError',
        'FeatureDisabled',
        'FeatureNotAvailable',
        'FixedFieldsAttributeDict',
        'Folder',
        'GraphTraversalRule',
        'GraphTraversalRules',
        'HashingError',
        'IncompatibleStorageSchema',
        'InputValidationError',
        'IntegrityError',
        'InternalError',
        'InvalidEntryPointTypeError',
        'InvalidOperation',
        'LicensingException',
        'LinkType',
        'LoadingEntryPointError',
        'LockedProfileError',
        'LockingProfileError',
        'MissingConfigurationError',
        'MissingEntryPointError',
        'ModificationNotAllowed',
        'MultipleEntryPointError',
        'MultipleObjectsError',
        'NotExistent',
        'NotExistentAttributeError',
        'NotExistentKeyError',
        'OutputParsingError',
        'ParsingError',
        'PluginInternalError',
        'ProfileConfigurationError',
        'ProgressReporterAbstract',
        'RemoteOperationError',
        'SandboxFolder',
        'StashMode',
        'StorageBackupError',
        'StorageMigrationError',
        'StoringNotAllowed',
        'SubmitTestFolder',
        'TQDM_BAR_FORMAT',
        'TestsNotAllowedError',
        'TransportTaskException',
        'UniquenessError',
        'UnstashTargetMode',
        'UnsupportedSchemaError',
        'UnsupportedSpeciesError',
        'ValidationError',
        'classproperty',
        'create_callback',
        'elements',
        'escape_for_bash',
        'escape_for_sql_like',
        'get_progress_reporter',
        'override',
        'override_log_level',
        'set_progress_bar_tqdm',
        'set_progress_reporter',
        'type_check',
        'url2pathname',
        'validate_link_label',
        'warn_deprecation',
    ),
    'aiida.engine': (
        'AiiDAPersister',
        'Awaitable',
        'AwaitableAction',
        'AwaitableTarget',
        'BaseRestartWorkChain',
        'CalcJob',
        'CalcJobImporter',
        'CalcJobOutputPort',
        'CalcJobProcessSpec',
        'DaemonClient',
        'ExitCode',
        'ExitCodesNamespace',
        'FunctionProcess',
        'InputPort',
        'InterruptableFuture',
        'JobManager',
        'JobsList',
        'ObjectLoader',
        'OutputPort',
        'PORT_NAMESPACE_SEPARATOR',
        'PastException',
        'PortNamespace',
        'PreSubmitException',
        'Process',
        'ProcessBuilder',
        'ProcessBuilderNamespace',
        'ProcessFuture',
        'ProcessHandlerReport',
        'ProcessSpec',
        'ProcessState',
        'Runner',
        'ToContext',
        'WithNonDb',
        'WithSerialize',
        'WorkChain',
        'append_',
        'assign_',
        'await_processes',
        'calcfunction',
        'construct_awaitable',
        'get_daemon_client',
        'get_object_loader',
        'if_',
        'interruptable_task',
        'is_process_function',
        'process_handler',
        'return_',
        'run',
        'run_get_node',
        'run_get_pk',
        'submit',
        'while_',
        'workfunction',
    ),
    'aiida.manage': (
        'AiiDAConfigDir',
        'AiiDAConfigPathResolver',
        'CURRENT_CONFIG_VERSION',
        'MIGRATIONS',
        'OLDEST_COMPATIBLE_CONFIG_VERSION',
        'Option',
        'Profile',
        'check_and_migrate_config',
        'config_needs_migrating',
        'disable_caching',
        'downgrade_config',
        'enable_caching',
        'get_current_version',
        'get_manager',
        'get_option',
        'get_option_names',
        'get_use_cache',
        'parse_option',
        'upgrade_config',
    ),
    'aiida.orm': (
        'ASCENDING',
        'AbstractCode',
        'AbstractNodeMeta',
        'ArrayData',
        'AttributeManager',
        'AuthInfo',
        'AutoGroup',
        'BandsData',
        'BaseType',
        'Bool',
        'CalcFunctionNode',
        'CalcJobNode',
        'CalcJobResultManager',
        'CalculationEntityLoader',
        'CalculationNode',
        'CifData',
        'Code',
        'CodeEntityLoader',
        'Collection',
        'Comment',
        'Computer',
        'ComputerEntityLoader',
        'ContainerizedCode',
        'DESCENDING',
        'Data',
        'Dict',
        'Entity',
        'EntityExtras',
        'EntityTypes',
        'EnumData',
        'Float',
        'FolderData',
        'Group',
        'GroupEntityLoader',
        'ImportGroup',
        'InstalledCode',
        'Int',
        'JsonableData',
        'Kind',
        'KpointsData',
        'LinkManager',
        'LinkPair',
        'LinkTriple',
        'List',
        'Log',
        'Node',
        'NodeAttributes',
        'NodeEntityLoader',
        'NodeLinksManager',
        'NodeRepository',
        'NumericType',
        'OrbitalData',
        'OrderSpecifier',
        'OrmEntityLoader',
        'OrmModel',
        'PortableCode',
        'ProcessNode',
        'ProjectionData',
        'QbField',
        'QbFieldFilters',
        'QbFields',
        'QueryBuilder',
        'RemoteData',
        'RemoteStashCompressedData',
        'RemoteStashCustomData',
        'RemoteStashData',
        'RemoteStashFolderData',
        'SinglefileData',
        'Site',
        'Str',
        'StructureData',
        'TrajectoryData',
        'UpfData',
        'UpfFamily',
        'User',
        'WorkChainNode',
        'WorkFunctionNode',
        'WorkflowNode',
        'XyData',
        'cif_from_ase',
        'deserialize_unsafe',
        'find_bandgap',
        'get_loader',
        'get_query_type_from_type_string',
        'get_type_string_from_class',
        'has_pycifrw',
        'load_code',
        'load_computer',
        'load_entity',
        'load_group',
        'load_node',
        'load_node_class',
        'pycifrw_from_cif',
        'serialize',
        'to_aiida_type',
        'validate_link',
    ),
    'aiida.parsers': ('Parser',),
    'aiida.plugins': (
        'BaseFactory',
        'BrokerFactory',
        'CalcJobImporterFactory',
        'CalculationFactory',
        'DataFactory',
        'DbImporterFactory',
        'GroupFactory',
        'OrbitalFactory',
        'ParserFactory',
        'PluginVersionProvider',
        'SchedulerFactory',
        'StorageFactory',
        'TransportFactory',
        'WorkflowFactory',
        'get_entry_point',
        'get_entry_point_from_class',
        'get_entry_point_from_string',
        'get_entry_point_names',
        'get_entry_points',
        'is_valid_entry_point_string',
        'load_entry_point',
        'load_entry_point_from_string',
        'parse_entry_point',
    ),
    'aiida.repository': (
        'AbstractRepositoryBackend',
        'DiskObjectStoreRepositoryBackend',
        'File',
        'FileType',
        'Repository',
        'SandboxRepositoryBackend',
    ),
    'aiida.restapi': (),
    'aiida.schedulers': (
        'BashCliScheduler',
        'JobInfo',
        'JobResource',
        'JobState',
        'JobTemplate',
        'MachineInfo',
        'NodeNumberJobResource',
        'ParEnvJobResource',
        'Scheduler',
        'SchedulerError',
        'SchedulerParsingError',
    ),
    'aiida.storage': ('SqliteDosStorage',),
    'aiida.tools': (
        'ArchiveExportError',
        'ArchiveImportError',
        'CalculationTools',
        'ExportImportException',
        'ExportValidationError',
        'Graph',
        'GroupNotFoundError',
        'GroupNotUniqueError',
        'GroupPath',
        'ImportUniquenessError',
        'ImportValidationError',
        'InvalidPath',
        'NoGroupsInPathError',
        'Orbital',
        'RealhydrogenOrbital',
        'WorkflowTools',
        'create_archive',
        'default_link_styles',
        'default_node_styles',
        'default_node_sublabels',
        'delete_group_nodes',
        'delete_nodes',
        'get_explicit_kpoints_path',
        'get_kpoints_path',
        'import_archive',
        'pstate_node_styles',
        'spglib_tuple_to_structure',
        'structure_to_spglib_tuple',
    ),
    'aiida.transports': (
        'AsyncSshTransport',
        'AsyncTransport',
        'BlockingTransport',
        'SshTransport',
        'Transport',
        'TransportPath',
        'convert_to_bool',
        'parse_sshconfig',
    ),
    'aiida.cmdline.params.arguments': (
        'CALCULATION',
        'CALCULATIONS',
        'CODE',
        'CODES',
        'COMPUTER',
        'COMPUTERS',
        'CONFIG_OPTION',
        'DATA',
        'DATUM',
        'GROUP',
        'GROUPS',
        'INPUT_FILE',
        'LABEL',
        'NODE',
        'NODES',
        'OUTPUT_FILE',
        'OverridableArgument',
        'PROCESS',
        'PROCESSES',
        'PROFILE',
        'PROFILES',
        'USER',
        'WORKFLOW',
        'WORKFLOWS',
    ),
    'aiida.cmdline.params.options': (
        'ALL',
        'ALL_STATES',
        'ALL_USERS',
        'ALSO_UNGROUPED',
        'APPEND_TEXT',
        'ARCHIVE_FORMAT',
        'BROKER_HOST',
        'BROKER_PASSWORD',
        'BROKER_PORT',
        'BROKER_PROTOCOL',
        'BROKER_USERNAME',
        'BROKER_VIRTUAL_HOST',
        'CALCULATION',
        'CALCULATIONS',
        'CALC_JOB_STATE',
        'CODE',
        'CODES',
        'COMPUTER',
        'COMPUTERS',
        'CONFIG_FILE',
        'CallableDefaultOption',
        'ConfigFileOption',
        'DATA',
        'DATUM',
        'DB_BACKEND',
        'DB_ENGINE',
        'DB_HOST',
        'DB_NAME',
        'DB_PASSWORD',
        'DB_PORT',
        'DB_USERNAME',
        'DEBUG',
        'DELETE_MISSING',
        'DESCRIPTION',
        'DICT_FORMAT',
        'DICT_KEYS',
        'DRY_RUN',
        'DUMP_UNSEALED',
        'END_DATE',
        'EXIT_STATUS',
        'EXPORT_FORMAT',
        'FAILED',
        'FILTER_BY_LAST_DUMP_TIME',
        'FLAT',
        'FORCE',
        'FORMULA_MODE',
        'FREQUENCY',
        'GROUP',
        'GROUPS',
        'GROUP_CLEAR',
        'HOSTNAME',
        'IDENTIFIER',
        'INCLUDE_ATTRIBUTES',
        'INCLUDE_EXTRAS',
        'INCLUDE_INPUTS',
        'INCLUDE_OUTPUTS',
        'INPUT_FORMAT',
        'INPUT_PLUGIN',
        'LABEL',
        'LIMIT',
        'MOST_RECENT_NODE',
        'MultipleValueOption',
        'NODE',
        'NODES',
        'NON_INTERACTIVE',
        'OLDER_THAN',
        'ONLY_TOP_LEVEL_CALCS',
        'ONLY_TOP_LEVEL_WORKFLOWS',
        'ORDER_BY',
        'ORDER_DIRECTION',
        'ORGANIZE_BY_GROUPS',
        'OVERWRITE',
        'OverridableOption',
        'PAST_DAYS',
        'PATH',
        'PAUSED',
        'PORT',
        'PREPEND_TEXT',
        'PRINT_TRACEBACK',
        'PROCESS_LABEL',
        'PROCESS_STATE',
        'PROFILE',
        'PROFILE_ONLY_CONFIG',
        'PROFILE_SET_DEFAULT',
        'PROJECT',
        'RAW',
        'RELABEL_GROUPS',
        'REPOSITORY_PATH',
        'SCHEDULER',
        'SILENT',
        'SORT',
        'START_DATE',
        'SYMLINK_CALCS',
        'TIMEOUT',
        'TRAJECTORY_INDEX',
        'TRANSPORT',
        'TRAVERSAL_RULE_HELP_STRING',
        'TYPE_STRING',
        'USER',
        'USER_EMAIL',
        'USER_FIRST_NAME',
        'USER_INSTITUTION',
        'USER_LAST_NAME',
        'VERBOSITY',
        'VISUALIZATION_FORMAT',
        'WITH_ELEMENTS',
        'WITH_ELEMENTS_EXCLUSIVE',
        'active_process_states',
        'graph_traversal_rules',
        'valid_calc_job_states',
        'valid_process_states',
    ),
    'aiida.cmdline.params.types': (
        'AbsolutePathParamType',
        'CalculationParamType',
        'CodeParamType',
        'ComputerParamType',
        'ConfigOptionParamType',
        'DataParamType',
        'EmailType',
        'EntryPointType',
        'FileOrUrl',
        'GroupParamType',
        'HostnameType',
        'IdentifierParamType',
        'LabelStringType',
        'LazyChoice',
        'MpirunCommandParamType',
        'MultipleValueParamType',
        'NodeParamType',
        'NonEmptyStringParamType',
        'PathOrUrl',
        'PluginParamType',
        'ProcessParamType',
        'ProfileParamType',
        'ShebangParamType',
        'UserParamType',
        'WorkflowParamType',
    ),
}


@pytest.mark.parametrize('package', PUBLIC_API.keys())
def test_public_api_snapshot(package):
    """The ``__all__`` of each public package must exactly match the frozen snapshot."""
    module = importlib.import_module(package)
    assert tuple(sorted(module.__all__)) == PUBLIC_API[package]


@pytest.mark.parametrize('package', PUBLIC_API.keys())
def test_public_api_resolvable(package):
    """Every public name must actually resolve on its package."""
    module = importlib.import_module(package)
    missing = [name for name in module.__all__ if not hasattr(module, name)]
    assert not missing, f'`{package}.__all__` contains unresolvable names: {missing}'


def test_public_api_no_private_names():
    """No public surface may leak underscore-prefixed names."""
    for package, names in PUBLIC_API.items():
        leaked = [name for name in names if name.startswith('_')]
        assert not leaked, f'`{package}` exposes private names: {leaked}'


def test_restapi_has_no_public_api():
    """``aiida.restapi`` is deliberately excluded from the public surface."""
    module = importlib.import_module('aiida.restapi')
    assert module.__all__ == ()


def test_all_second_level_packages_accounted_for():
    """Every second-level package must be either snapshotted or explicitly surface-free.

    This is the guard that makes the lock complete: a *new* second-level package, or a package
    that gains a public ``__all__``, would otherwise slip into the public API without failing CI.
    """
    snapshotted = {package for package in PUBLIC_API if package.count('.') == 1}
    actual = {f'aiida.{info.name}' for info in pkgutil.iter_modules(aiida.__path__) if info.ispkg}
    accounted = snapshotted | SURFACE_FREE

    unaccounted = actual - accounted
    assert not unaccounted, (
        f'second-level package(s) with no public-API decision: {sorted(unaccounted)}. '
        'Add each to PUBLIC_API (to freeze its surface) or to SURFACE_FREE (if intentionally private).'
    )

    stale = accounted - actual
    assert not stale, f'snapshot references package(s) that no longer exist: {sorted(stale)}'


@pytest.mark.parametrize('package', sorted(SURFACE_FREE))
def test_surface_free_packages_stay_private(package):
    """A surface-free package must not acquire a public ``__all__``."""
    module = importlib.import_module(package)
    exposed = getattr(module, '__all__', ())
    assert exposed == (), (
        f'`{package}` gained a public surface {tuple(exposed)}; the generator will publish it. '
        'Freeze it in PUBLIC_API or keep it surface-free.'
    )
