---
label: add
description: add
input_plugin: arithmetic.add
on_computer: true
computer: localhost
remote_abs_path: /home/runner/work/aiida-core/aiida-core/.ci/add.sh
prepend_text: ' '
append_text: ' '
