---
label: doubler
description: doubler
input_plugin: templatereplacer
on_computer: true
computer: localhost
remote_abs_path: /home/runner/work/aiida-core/aiida-core/.ci/doubler.sh
prepend_text: ' '
append_text: ' '
