---
label: localhost
description: localhost
hostname: localhost
transport: local
scheduler: direct
shebang: '#!/usr/bin/env bash'
work_dir: /home/runner/work/aiida-core/aiida-core
mpirun_command: ' '
mpiprocs_per_machine: 1
prepend_text: ' '
append_text: ' '