---
label: slurm-ssh
description: slurm container
hostname: slurm
transport: ssh
scheduler: slurm
shebang: "#!/bin/bash"
work_dir: /home/{username}/workdir
mpirun_command: "mpirun -np {tot_num_mpiprocs}"
mpiprocs_per_machine: 1
prepend_text: ""
append_text: ""
