###########################################################################
# Copyright (c), The AiiDA team. All rights reserved.                     #
# This file is part of the AiiDA code.                                    #
#                                                                         #
# The code is hosted on GitHub at https://github.com/aiidateam/aiida-core #
# For further information on the license, see the LICENSE.txt file        #
# For further information please visit http://www.aiida.net               #
###########################################################################
"""Local state of a collab: the per-peer sync cursors and the log of pull and push events.

This state is deliberately kept local to the profile and is never shared with peers. It lives next to the configuration
instead of inside it, because the event log grows with every sync whereas the configuration is read on every ``verdi``
invocation.
"""

from __future__ import annotations

import json
import os
import sys
from contextlib import contextmanager
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any, Literal

if TYPE_CHECKING:
    from collections.abc import Iterator

    from aiida.manage.configuration import Profile

Direction = Literal['pull', 'push']


@contextmanager
def _exclusive_lock(filepath: Path) -> Iterator[None]:
    """Hold an exclusive advisory lock on the state stored at ``filepath``.

    The lock lives on a sidecar file, because ``save`` replaces the state file itself.
    """
    lockpath = filepath.with_name(f'{filepath.name}.lock')
    lockpath.parent.mkdir(parents=True, exist_ok=True)

    with lockpath.open('w') as handle:
        # On Windows there is no ``fcntl``, so writers there stay unguarded, as all writers are on any platform
        # before the daemon serves the collab endpoint and becomes the second one.
        if sys.platform != 'win32':
            import fcntl

            fcntl.flock(handle, fcntl.LOCK_EX)

        yield


@dataclass
class CollabEvent:
    """A single completed pull or push."""

    time: datetime
    direction: Direction
    peer: str
    uuids: list[str]
    size: int

    def as_dict(self) -> dict[str, Any]:
        return {
            'time': self.time.isoformat(),
            'direction': self.direction,
            'peer': self.peer,
            'uuids': self.uuids,
            'size': self.size,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> CollabEvent:
        return cls(
            time=datetime.fromisoformat(data['time']),
            direction=data['direction'],
            peer=data['peer'],
            uuids=data['uuids'],
            size=data['size'],
        )


@dataclass
class CollabState:
    """The local state of the collab of a single profile.

    The cursors record, per peer, the export instant of the last delta imported from that peer: "I hold a snapshot
    of everything that was in this peer's profile at T". A cursor advances only on a successful import — identically
    for pulls and received pushes — and every instant it is compared against is generated by that same peer, so
    clocks never cross.
    """

    filepath: Path
    cursors: dict[str, datetime] = field(default_factory=dict)
    events: list[CollabEvent] = field(default_factory=list)
    pending_links: list[list[str]] = field(default_factory=list)
    """Boundary links of a thin delta, as ``[input_uuid, output_uuid, type, label]``, journalled before the import
    and cleared once they are written: the import commits its own transaction, so a crash between the two would
    otherwise lose the links between imported nodes and the ones already held."""

    @staticmethod
    def get_filepath(profile: Profile) -> Path:
        """Return the path of the file in which the state of the collab of ``profile`` is stored.

        Keyed by the UUID of the profile rather than its name, so that a profile recreated under the name of a
        deleted one does not inherit its cursors — which would make a pull skip nodes for no visible reason.
        """
        from aiida.manage.configuration.settings import AiiDAConfigPathResolver

        return AiiDAConfigPathResolver().collab_dir / f'{profile.uuid}.json'

    @staticmethod
    def get_workdir(profile: Profile) -> Path:
        """Return the directory in which the transfer files of the collab of ``profile`` live."""
        from aiida.manage.configuration.settings import AiiDAConfigPathResolver

        return AiiDAConfigPathResolver().collab_dir / str(profile.uuid)

    @classmethod
    def load(cls, profile: Profile) -> CollabState:
        """Load the state of the collab of ``profile``."""
        return cls.read(cls.get_filepath(profile))

    @classmethod
    def read(cls, filepath: Path) -> CollabState:
        """Read the state stored at ``filepath``; a missing file is empty state, not an error."""
        if not filepath.exists():
            return cls(filepath=filepath)

        data = json.loads(filepath.read_text(encoding='utf-8'))

        return cls(
            filepath=filepath,
            cursors={peer: datetime.fromisoformat(value) for peer, value in data.get('cursors', {}).items()},
            events=[CollabEvent.from_dict(event) for event in data['events']],
            pending_links=data.get('pending_links', []),
        )

    def save(self) -> None:
        """Write the state to disk, replacing the existing file atomically."""
        import tempfile

        from aiida.manage.configuration.settings import DEFAULT_UMASK

        data = {
            'cursors': {peer: cursor.isoformat() for peer, cursor in self.cursors.items()},
            'events': [event.as_dict() for event in self.events],
            'pending_links': self.pending_links,
        }

        umask = os.umask(DEFAULT_UMASK)

        try:
            self.filepath.parent.mkdir(parents=True, exist_ok=True)

            # The temporary file has to live in the same directory for ``os.replace`` to be atomic, and has to have a
            # unique name because another process can be writing the state of the same profile at the same time.
            with tempfile.NamedTemporaryFile(
                dir=self.filepath.parent, delete=False, mode='w', encoding='utf-8'
            ) as handle:
                json.dump(data, handle, indent=4)
                filepath_temporary = handle.name
        finally:
            os.umask(umask)

        os.replace(filepath_temporary, self.filepath)

    def imported_uuids_since(self, instant: datetime | None) -> set[str]:
        """Return the UUIDs of every node imported from any peer since ``instant``, or ever when ``None``.

        Received pushes are recorded with direction ``pull`` too — the direction describes the flow relative to this
        profile — so this is the complete set of nodes that entered the profile through the collab.
        """
        return {
            uuid
            for event in self.events
            if event.direction == 'pull' and (instant is None or event.time >= instant)
            for uuid in event.uuids
        }

    @classmethod
    @contextmanager
    def mutate(cls, filepath: Path) -> Iterator[CollabState]:
        """Read the state stored at ``filepath`` under an exclusive lock and save it on exit.

        Every writer has to mutate through this: the CLI and the collab endpoint of the daemon share the state
        file, and an unguarded read-modify-write cycle loses whichever of two concurrent writes finishes first.
        """
        with _exclusive_lock(filepath):
            state = cls.read(filepath)
            yield state
            state.save()


@contextmanager
def import_lock(filepath: Path) -> Iterator[None]:
    """Hold the import lock of the profile whose state is stored at ``filepath``, waiting for it if necessary.

    Every import into the profile — a CLI pull as much as a push received by the collab endpoint — runs under this
    lock, so two of them can never interleave. The endpoint's push handshake answers busy while it is held, which is
    what serializes concurrent fan-in before any bytes travel.
    """
    lockpath = filepath.with_name(f'{filepath.name}.import.lock')
    lockpath.parent.mkdir(parents=True, exist_ok=True)

    with lockpath.open('w') as handle:
        # Same Windows caveat as ``_exclusive_lock``: without ``fcntl`` imports stay unguarded there.
        if sys.platform != 'win32':
            import fcntl

            fcntl.flock(handle, fcntl.LOCK_EX)

        yield


def import_lock_held(filepath: Path) -> bool:
    """Return whether an import into the profile whose state is stored at ``filepath`` is running right now."""
    if sys.platform == 'win32':
        return False

    import fcntl

    lockpath = filepath.with_name(f'{filepath.name}.import.lock')

    if not lockpath.exists():
        return False

    with lockpath.open('w') as handle:
        try:
            fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except OSError:
            return True

        fcntl.flock(handle, fcntl.LOCK_UN)
        return False


def delete_state(profile: Profile) -> None:
    """Remove the collab state and transfer files of a profile, called when the profile itself is deleted.

    Collab state must not outlive its profile: it describes what this profile holds of its peers, which a
    recreated profile of the same name holds nothing of.
    """
    import shutil

    filepath = CollabState.get_filepath(profile)

    for suffix in ('', '.lock', '.import.lock'):
        filepath.with_name(f'{filepath.name}{suffix}').unlink(missing_ok=True)

    shutil.rmtree(CollabState.get_workdir(profile), ignore_errors=True)
