###########################################################################
# Copyright (c), The AiiDA team. All rights reserved.                     #
# This file is part of the AiiDA code.                                    #
#                                                                         #
# The code is hosted on GitHub at https://github.com/aiidateam/aiida-core #
# For further information on the license, see the LICENSE.txt file        #
# For further information please visit http://www.aiida.net               #
###########################################################################
"""Export and import the delta of provenance that a profile shares with the peers of its collab."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast

from aiida import orm
from aiida.common import timezone
from aiida.common.links import GraphTraversalRules
from aiida.common.log import AIIDA_LOGGER
from aiida.orm.utils.mixins import Sealable
from aiida.tools.collab.state import CollabState
from aiida.tools.graph.graph_traversers import get_nodes_export, traverse_graph, validate_traversal_rules

if TYPE_CHECKING:
    from aiida.orm.implementation import StorageBackend

# Callers are left out: a process that is still running has sealed children but is not sealed itself, and the export
# refuses to write an unsealed process. Their CALL links travel once the caller seals.
TRAVERSAL_RULES: dict[str, Any] = {'call_calc_backward': False, 'call_work_backward': False}

LOGGER = AIIDA_LOGGER.getChild('collab')


# Link types of which a node can have at most one incoming, mapped to the class they are exclusive against:
# a data node has exactly one creator, a process exactly one caller of either call flavour.
def seed_filters(cursor: datetime | None) -> dict[str, Any]:
    """Return the query filters selecting the seeds of a delta: the sealed processes produced since ``cursor``."""
    filters: dict[str, Any] = {f'attributes.{Sealable.SEALED_KEY}': True}

    if cursor is not None:
        filters['mtime'] = {'>=': cursor}

    return filters


@dataclass
class Delta:
    """The provenance-closed delta computed for a presented cursor and claim, before any archive is built.

    The manifest — its node UUIDs — is what the negotiation serves; the links are kept so that a later export of a
    subset knows which links cross the subset's boundary.
    """

    uuid_by_pk: dict[int, str]
    links: list[Any]
    instant: datetime
    """The export instant the importer stores as its cursor for this profile once the import succeeds."""

    @property
    def uuids(self) -> list[str]:
        """The manifest: the UUIDs of every node of the closed delta."""
        return sorted(self.uuid_by_pk.values())


@dataclass
class DeltaExport:
    """An archive built from a delta, holding the subset of it that the requester asked for."""

    filepath: Path
    uuids: list[str]
    instant: datetime


def compute_delta(
    *,
    state: CollabState,
    backend: StorageBackend,
    cursor: datetime | None,
    claim: frozenset[str] | set[str] = frozenset(),
) -> Delta:
    """Compute everything that entered this profile since the requester's cursor.

    The delta starts from the sealed processes produced since ``cursor`` united with the nodes this profile itself
    imported since then — imported nodes keep their original timestamps, so without the event union provenance
    relayed through this profile would never reach the requester. Nodes the requester claims to hold are dropped
    from that start set; the delta is then closed over inputs, outputs and called processes, so a claimed node
    that the remaining provenance requires is still part of it, which is safe because the requester has it.

    The sender keeps no record of what it served: the requester advances its cursor to the returned instant only
    once it imported a delta.

    :param state: the state of the collab, whose event log supplies the imported nodes.
    :param backend: the storage to compute from.
    :param cursor: the export instant of the last delta the requester imported from this profile, or ``None`` for
        everything. Every instant it is compared against was generated by this profile, so clocks never cross.
    :param claim: UUIDs the requester already holds and does not want re-delivered.
    """
    # Taken before querying, so a process that seals during the computation is picked up by the next one.
    instant = timezone.now()

    seeds = orm.QueryBuilder(backend=backend).append(orm.ProcessNode, filters=seed_filters(cursor)).all(flat=True)
    seed_pks = {node.pk for node in seeds}
    start = {node.pk: node for node in seeds + _imported_nodes(state, cursor, backend)}
    kept = [node for node in start.values() if node.uuid not in claim]
    nodes = _without_unsealed_provenance(kept, backend=backend)

    # A withheld seed has to stay within reach of the next computation, and nothing will touch its mtime when its
    # child seals, so the instant cannot move past it. The seed filter is inclusive for that reason. Imported nodes
    # cannot be withheld: every export rule that could reach a local unsealed process from them is off by default.
    kept_pks = {cast(int, node.pk) for node in nodes}
    withheld = [node for node in kept if node.pk not in kept_pks and node.pk in seed_pks]

    if withheld:
        instant = min(node.mtime for node in withheld)

    traversed = get_nodes_export(starting_pks=kept_pks, get_links=True, backend=backend, **TRAVERSAL_RULES)
    pks = traversed['nodes']
    links = list(traversed['links'] or [])

    uuid_by_pk = {}

    if pks:
        query = orm.QueryBuilder(backend=backend).append(orm.Node, filters={'id': {'in': pks}}, project=['id', 'uuid'])
        uuid_by_pk = dict(query.iterall())

    return Delta(uuid_by_pk=uuid_by_pk, links=links, instant=instant)


def export_delta(
    filepath: Path,
    *,
    delta: Delta,
    backend: StorageBackend,
    want: frozenset[str] | set[str] | None = None,
) -> DeltaExport:
    """Write the requested subset of a delta to an archive.

    The archive is not provenance-closed: it holds exactly the nodes of ``want``, and the links that cross from
    them to nodes the requester already holds travel in the archive metadata as UUID quadruples, to be re-attached
    by the import. This is what keeps already-held ancestors — rows and repository files alike — off the wire;
    closure was already guaranteed when the delta was computed.

    :param filepath: the path to write the archive to.
    :param delta: the computed delta the subset is taken from.
    :param backend: the storage to export from.
    :param want: the UUIDs the requester asked for, or ``None`` for the whole delta.
    """
    want_uuids = set(delta.uuid_by_pk.values()) if want is None else set(want) & set(delta.uuid_by_pk.values())
    want_pks = {pk for pk, uuid in delta.uuid_by_pk.items() if uuid in want_uuids}

    internal = []
    boundary = []

    for link in delta.links:
        in_want = (link.source_id in want_pks) + (link.target_id in want_pks)

        if in_want == 2:
            internal.append(link)
        elif in_want == 1:
            boundary.append(
                [delta.uuid_by_pk[link.source_id], delta.uuid_by_pk[link.target_id], link.link_type, link.link_label]
            )

    _write_thin_archive(filepath, backend=backend, node_pks=want_pks, links=internal, boundary=boundary)

    return DeltaExport(filepath=filepath, uuids=sorted(want_uuids), instant=delta.instant)


def _write_thin_archive(
    filepath: Path,
    *,
    backend: StorageBackend,
    node_pks: set[int],
    links: list[Any],
    boundary: list[list[str]],
) -> None:
    """Write an archive of exactly the given nodes, with the links that leave the set in the metadata.

    Mirrors the streaming of ``create_archive`` — the same rows, checkpoint stripping and repository objects — but
    without its traversal, which would close the set again and pull the already-held ancestors back in. The archive
    is self-consistent (every link row has both endpoints in it), so any reader can open it; only the metadata key
    carries the collab-specific boundary.
    """
    from aiida.common.utils import DEFAULT_BATCH_SIZE, DEFAULT_FILTER_SIZE, batch_iter
    from aiida.orm.entities import EntityTypes
    from aiida.tools.archive.common import entity_type_to_orm
    from aiida.tools.archive.create import _stream_repo_files
    from aiida.tools.archive.implementations.sqlite_zip.main import ArchiveFormatSqlZip

    def related_pks(entity: Any, relationship: str) -> set[int]:
        if not node_pks:
            return set()

        kwargs: dict[str, Any] = {relationship: 'node'}
        query = (
            orm.QueryBuilder(backend=backend)
            .append(orm.Node, filters={'id': {'in': node_pks}}, tag='node')
            .append(entity, project='id', **kwargs)
            .distinct()
        )
        return set(query.all(flat=True))

    entity_pks: dict[EntityTypes, set[int]] = {
        EntityTypes.USER: related_pks(orm.User, 'with_node'),
        EntityTypes.COMPUTER: related_pks(orm.Computer, 'with_node'),
        EntityTypes.NODE: node_pks,
        EntityTypes.COMMENT: related_pks(orm.Comment, 'with_node'),
        EntityTypes.LOG: related_pks(orm.Log, 'with_node'),
    }

    if comment_pks := entity_pks[EntityTypes.COMMENT]:
        query = (
            orm.QueryBuilder(backend=backend)
            .append(orm.Comment, filters={'id': {'in': comment_pks}}, tag='comment')
            .append(orm.User, with_comment='comment', project='id')
            .distinct()
        )
        entity_pks[EntityTypes.USER].update(query.all(flat=True))

    archive_format = ArchiveFormatSqlZip()

    with archive_format.open(filepath, mode='w') as writer:
        writer.update_metadata(
            {
                'ctime': timezone.now().isoformat(),
                'creation_parameters': {'collab_thin_delta': True},
                'collab_boundary_links': boundary,
            }
        )

        def transform(row: dict[str, Any]) -> dict[str, Any]:
            data = row['entity']
            if data.get('node_type', '').startswith('process.'):
                data['attributes'].pop(orm.ProcessNode.CHECKPOINT_KEY, None)
            return data

        for etype, pks in entity_pks.items():
            if not pks:
                continue

            entity_rows = (
                orm.QueryBuilder(backend=backend)
                .append(entity_type_to_orm[etype], filters={'id': {'in': pks}}, tag='entity', project=['**'])
                .iterdict(batch_size=DEFAULT_BATCH_SIZE)
            )

            for _, rows in batch_iter(entity_rows, DEFAULT_BATCH_SIZE, transform):
                writer.bulk_insert(etype, rows)

        link_rows = [
            {'input_id': link.source_id, 'output_id': link.target_id, 'label': link.link_label, 'type': link.link_type}
            for link in links
        ]

        for _, rows in batch_iter(link_rows, DEFAULT_BATCH_SIZE, lambda row: row):
            writer.bulk_insert(EntityTypes.LINK, rows, allow_defaults=True)

        if node_pks:
            _stream_repo_files(
                archive_format.key_format, writer, node_pks, backend, DEFAULT_BATCH_SIZE, DEFAULT_FILTER_SIZE
            )


def _imported_nodes(state: CollabState, cursor: datetime | None, backend: StorageBackend) -> list[orm.Node]:
    """Return the nodes this profile imported since ``cursor`` that still exist locally."""
    uuids = state.imported_uuids_since(cursor)

    if not uuids:
        return []

    return orm.QueryBuilder(backend=backend).append(orm.Node, filters={'uuid': {'in': sorted(uuids)}}).all(flat=True)


def _without_unsealed_provenance(nodes: list[orm.Node], *, backend: StorageBackend) -> list[orm.Node]:
    """Return the start nodes whose provenance does not reach a process that is still running.

    A process that excepted is sealed even though a process it called can still be running, and the export refuses to
    write an unsealed process. Since the rules that pull in called processes cannot be turned off, such a seed has to
    be left out entirely; it travels once its child seals.
    """
    if not nodes:
        return nodes

    nodes_by_pk = {cast(int, node.pk): node for node in nodes}
    unsealed = _unsealed_pks(backend, get_nodes_export(nodes_by_pk.keys(), backend=backend, **TRAVERSAL_RULES)['nodes'])

    if not unsealed:
        return nodes

    # Which seeds reach an unsealed process is answered by walking the export in reverse from the unsealed ones, so
    # that it costs one traversal rather than one per seed.
    rules = validate_traversal_rules(GraphTraversalRules.EXPORT, **TRAVERSAL_RULES)
    reaching = traverse_graph(
        unsealed, backend=backend, links_forward=rules['backward'], links_backward=rules['forward']
    )['nodes']

    return [node for pk, node in nodes_by_pk.items() if pk not in reaching]


def _unsealed_pks(backend: StorageBackend, pks: set[int]) -> set[int]:
    """Return the primary keys of the processes among ``pks`` that are not sealed."""

    def query(**filters: Any) -> set[int]:
        return set(
            orm.QueryBuilder(backend=backend)
            .append(orm.ProcessNode, filters={'id': {'in': list(pks)}, **filters}, project='id')
            .all(flat=True)
        )

    # Queried as the complement of the sealed processes, because an unsealed one has no ``sealed`` attribute at all.
    return query() - query(**{f'attributes.{Sealable.SEALED_KEY}': True})
