# -*- coding: utf-8 -*-

from aiida.orm.implementation.calculation import Calculation



class WorkCalculation(Calculation):
    """
    Used to represent a calculation generated by a Process from the new
    workflows system.
    """
    pass