- name: Run tests against environment
  hosts: all
  gather_facts: false

  # run as aiida user
  become: true
  become_method: "{{ become_method }}"
  become_user: "{{ aiida_user }}"

  environment:
    AIIDA_PATH: "{{ aiida_path }}"

  vars:
    aiida_add_code: "add"

  tasks:

  - name: "Check if add code is already present"
    shell: "{{ venv_bin }}/verdi -p {{ aiida_backend }} code show {{ aiida_add_code }}@localhost"
    ignore_errors: true
    changed_when: false
    no_log: true
    register: aiida_check_code

  - name: verdi add code setup
    when: aiida_check_code.rc != 0
    shell: >
      {{ venv_bin }}/verdi -p {{ aiida_backend }} code setup
      -D "simple script that adds two numbers"
      -n -L {{ aiida_add_code }} -P arithmetic.add
      -Y localhost --remote-abs-path=/bin/bash

  - name: Copy workchain files
    copy:
      src: polish
      dest: "${HOME}/{{ aiida_backend }}"

  - name: get python path including workchains
    shell: echo "${PYTHONPATH}:${HOME}/{{ aiida_backend }}/polish"
    register: echo_pythonpath

  - set_fact:
      aiida_pythonpath: "{{ echo_pythonpath.stdout }}"

  - name: Reset pythonpath of daemon workers
    # note `verdi daemon restart` did not seem to update the environmental variables?
    shell: |
      {{ venv_bin }}/verdi -p {{ aiida_backend }} daemon stop
      {{ venv_bin }}/verdi -p {{ aiida_backend }} daemon start {{ aiida_workers }}
    environment:
      PYTHONPATH: "{{ aiida_pythonpath }}"

  - name: run polish notation workchains (parallel)
    include_tasks: run_polish_parallel.yml
    vars:
      polish_script: "${HOME}/{{ aiida_backend }}/polish/cli.py"
      polish_timeout: 600
      all_expressions:
        - "1 -2 -1 4 -5 -5 * * * * +"
        - "2 1 3 3 -1 + ^ ^ +"
        - "3 -5 -1 -4 + * ^"
        - "2 4 2 -4 * * +"
        - "3 1 1 5 ^ ^ ^"
        - "3 1 3 4 -4 2 * + + ^ ^"
      polish_expressions: "{{ item }}"
    loop: "{{ all_expressions | batch(6) | list }}"
