Node data:
  label: multiply
  description: ''
  pk: 47371
  uuid: 0b5cf0ad-9acf-48f9-9577-920ad1a6be90
  ctime: 2025-03-26 10:06:40.332044+00:00
  mtime: 2025-03-26 10:06:41.157341+00:00
  node_type: process.calculation.calcfunction.CalcFunctionNode.
  process_type: aiida.workflows.arithmetic.multiply_add.multiply
  is_finished_ok: true
User data:
  first_name: ''
  last_name: ''
  email: aiida@localhost
  institution: ''
Node attributes:
  process_state: finished
  process_label: multiply
  metadata_inputs: null
  version:
    core: 2.6.2.post0
    plugin: 2.6.2.post0
  function_name: multiply
  function_starting_line_number: 19
  function_number_of_lines: 3
  function_namespace: aiida.workflows.arithmetic.multiply_add
  exit_status: 0
  sealed: true
Node extras:
  _aiida_hash: 23dce350425dcc967827a2933c3d500f43892c8e43052c2648820fa9681af171
