version: '3.4'

services:

  aiida:
    image: ${REGISTRY:-}${AIIDA_CORE_WITH_SERVICES_IMAGE:-aiidateam/aiida-core-with-services}${TAG:-}
    environment:
      TZ: Europe/Zurich
      SETUP_DEFAULT_AIIDA_PROFILE: 'true'
        #volumes:
        #    - aiida-home-folder:/home/aiida

volumes:
  aiida-home-folder:
