name: ci-code

on:
  push:
    branches-ignore: [gh-pages]
  pull_request:
    branches-ignore: [gh-pages]
    paths-ignore: [docs/**]

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
    # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:
    uses: ./.github/workflows/ci-code-reusable.yml
    secrets: inherit
