name: docs-build

on:
  push:
    branches-ignore: [gh-pages]
  pull_request:
    branches-ignore: [gh-pages]
    paths: [docs/**]

env:
  FORCE_COLOR: 1

jobs:

  docs-linkcheck:

    runs-on: ubuntu-24.04
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Install aiida-core and docs deps
      uses: ./.github/actions/install-aiida-core
      with:
        python-version: '3.9'
        extras: docs,tests,rest,atomic_tools
        from-lock: 'false'

    - name: Build HTML docs
      id: linkcheck
      run: |
        make -C docs html linkcheck 2>&1 | tee check.log
        echo "::set-output name=broken::$(grep '(line\s*[0-9]*)\(\s\)broken\(\s\)' check.log)"
      env:
        SPHINXOPTS: -nW --keep-going

    - name: Show docs build check results
      run: |
        if [ -z "${{ steps.linkcheck.outputs.broken }}" ]; then
            echo "No broken links found."
            exit 0
        else
            echo "Broken links found:"
            echo "${{ steps.linkcheck.outputs.broken }}"
            exit 1
        fi
