name: pre-commit
# NOTE: This job is not duplicating pre-commit.ci job,
# since that once skips running mypy type-checking
# due to technical limitations of pre-commit.ci runners.

on:
  push:
    branches-ignore: [gh-pages]
  pull_request:
    branches-ignore: [gh-pages]

jobs:

  static-checks:
    uses: ./.github/workflows/pre-commit-reusable.yml
