name: ci-checks
# NOTE: This job is not duplicating pre-commit.ci job,
# since that once skips running mypy type-checking
# due to technical limitations of pre-commit.ci runners.

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches-ignore: [gh-pages]
  workflow_dispatch:

jobs:

  checks:
    if: github.event_name != 'pull_request' || !contains(fromJson(toJson(github.event.pull_request.labels)).*.name, 'test-release')
    uses: ./.github/workflows/pre-commit-reusable.yml
