name: rabbitmq

on:
    push:
        branches-ignore: [gh-pages]
    pull_request:
        branches-ignore: [gh-pages]
        paths-ignore: ['docs/**']

jobs:

    tests:

        runs-on: ubuntu-latest
        timeout-minutes: 30

        strategy:
            fail-fast: false
            matrix:
                rabbitmq: ['3.6', '3.7', '3.8']

        services:
            postgres:
                image: postgres:10
                env:
                    POSTGRES_DB: test_aiida
                    POSTGRES_PASSWORD: ''
                    POSTGRES_HOST_AUTH_METHOD: trust
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                -   5432:5432
            rabbitmq:
                image: rabbitmq:${{ matrix.rabbitmq }}-management
                ports:
                -   5672:5672
                -   15672:15672

        steps:
        -   uses: actions/checkout@v2

        -   name: Set up Python 3.8
            uses: actions/setup-python@v2
            with:
                python-version: '3.8'

        -   name: Install system dependencies
            run: sudo apt update && sudo apt install postgresql

        -   name: Upgrade pip
            run: |
                pip install --upgrade pip
                pip --version

        -   name: Install aiida-core
            run: |
                pip install -r requirements/requirements-py-3.8.txt
                pip install --no-deps -e .
                pip freeze

        -   name: Run tests
            run: pytest -sv -k 'requires_rmq'
