name: rabbitmq

on:
  push:
    branches-ignore: [gh-pages]
  pull_request:
    branches-ignore: [gh-pages]
    paths-ignore: [docs/**]

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
    # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        rabbitmq-version: ['3.6', '3.7', '3.8']

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_DB: test_aiida
          POSTGRES_PASSWORD: ''
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432
      rabbitmq:
        image: rabbitmq:${{ matrix.rabbitmq-version }}-management
        ports:
        - 5672:5672
        - 15672:15672

    steps:
    - uses: actions/checkout@v4

    - name: Install aiida-core
      uses: ./.github/actions/install-aiida-core

    - name: Install system dependencies
      run: sudo apt update && sudo apt install postgresql

    - name: Run tests
      run: pytest -sv -k 'requires_rmq'
