name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]

jobs:
  slash_command_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          commands: run-ci
          reaction-type: hooray
